name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Test Auto Deploy On Main Repo
    runs-on: ubuntu-latest

    steps:
      - run: |
      curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/MooKorea/MooKorea.github.io/actions/workflows/build.yaml/dispatches --data '{"ref": "master"}'